<a href="https://colab.research.google.com/github/sklee01061/AIPython/blob/main/AI_%ED%8C%8C%EC%9D%B4%EC%8D%AC_5_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.arange(1, 10, 2)
print(array1)

[1 3 5 7 9]


In [2]:
array2 = np.ones((3, 4))
print(array2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
array3 = np.linspace(0, 1, 10)
print(array3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [4]:
import numpy as np
arr1 = np.ones([3,4])
print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [5]:
import numpy as np

# 1. A행렬 생성
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# 2. A의 모양(shape) 출력
print("Shape of A:", A.shape)

# 3. 19 값을 추출
value_19 = A[3, 3]
print("Value at position (3, 3):", value_19)

# 4. [[1, 2], [6, 7]] 값을 추출
slice1 = A[:2, :2]
print("Sliced array 1:")
print(slice1)

# 5. [[19, 20], [24, 25]] 값을 추출
slice2 = A[3:5, 3:5]
print("Sliced array 2:")
print(slice2)

# 6. 0축의 첫 번째 행과 두 번째 행을 추출
rows = A[:2, :]
print("Rows 1 and 2:")
print(rows)

# 7. 1축의 마지막 열과 마지막 직전 열을 추출
columns = A[:, -2:]
print("Last two columns:")
print(columns)


Shape of A: (5, 5)
Value at position (3, 3): 19
Sliced array 1:
[[1 2]
 [6 7]]
Sliced array 2:
[[19 20]
 [24 25]]
Rows 1 and 2:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last two columns:
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]
